dist: jammy
sudo: required
language: python
python: "3.8"

before_install:
  - nvm install 16

install:
  - echo -e '@neverendingsupport:registry=https://registry.nes.herodevs.com/npm/pkg/\n//registry.nes.herodevs.com/npm/pkg/:_authToken="'${NES_AUTH_TOKEN}'"' > .npmrc
  - npm install
  - pip3 install tox

script:
  - psql -c 'create database pazuzu_test;' -U postgres
  - psql pazuzu_test -c 'create extension pg_trgm;' -U postgres
  - psql pazuzu_test -c 'create role diablo superuser login; alter schema public owner to diablo;' -U postgres
  - pip3 install -r requirements.txt
  - tox --parallel || travis_terminate 1

services:
  - postgresql
